import time
import requests
import argparse
import os
import json

from src.red_team import RedTeamPoisoner
from src.blue_team import BlueTeamGuardrail

def compute_metrics(results):
    """
    Computes False Positive Rate and False Negative Rate for Simulation Mode.
    """
    TP = TN = FP = FN = ERR = 0
    
    for r in results:
        t = r.get("true_label", -1)
        p = r.get("predicted_label", -1)
        
        if p == -1: 
            ERR += 1
            continue
        if t == 1 and p == 1: 
            TP += 1
        elif t == 0 and p == 0: 
            TN += 1
        elif t == 0 and p == 1: 
            FP += 1
        elif t == 1 and p == 0: 
            FN += 1
            
    total_benign = TN + FP
    total_malicious = TP + FN
    
    fpr = (FP / total_benign) if total_benign > 0 else 0.0
    fnr = (FN / total_malicious) if total_malicious > 0 else 0.0
    
    return {
        "Total processed": len(results),
        "True Positives": TP, 
        "True Negatives": TN,
        "False Positives": FP, 
        "False Negatives": FN,
        "Errors": ERR,
        "False Positive Rate (FPR)": fpr,
        "False Negative Rate (FNR)": fnr
    }

def extract_high_risk_fields(item):
    """
    Extracts specific fields prone to prompt injection from standard 
    KAPE or Velociraptor JSON artifacts.
    """
    high_risk_keys = [
        "CommandLine", "FileDescription", "ExecutablePath", 
        "ImagePath", "Arguments", "ParentCommandLine",
        "PayloadData", "Message"
    ]
    
    extracted_content = []
    for key, value in item.items():
        if any(risk_key.lower() in key.lower() for risk_key in high_risk_keys) and value:
            extracted_content.append(f"{key}: {value}")
            
    return "\n".join(extracted_content)

def load_real_data(input_dir):
    """
    Scans a directory and parses real artifacts generated by KAPE or Velociraptor.
    """
    dataset = []
    if not os.path.exists(input_dir):
        print(f"Error: Input directory {input_dir} does not exist.")
        return dataset

    for filename in os.listdir(input_dir):
        if filename.endswith(".json"):
            filepath = os.path.join(input_dir, filename)
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    
                    if isinstance(data, list):
                        for item in data:
                            if isinstance(item, dict):
                                relevant_text = extract_high_risk_fields(item)
                                if relevant_text:
                                    dataset.append({"artifact_source": filename, "content": relevant_text})
                    elif isinstance(data, dict):
                        relevant_text = extract_high_risk_fields(data)
                        if relevant_text:
                            dataset.append({"artifact_source": filename, "content": relevant_text})
            except Exception as e:
                print(f"Warning: Failed to parse {filename} - {e}")
                
    return dataset

def main():
    parser = argparse.ArgumentParser(description="DFIR-Guardrail Pipeline")
    parser.add_argument("--input_dir", type=str, help="Path to parsed artifacts from KAPE or Velociraptor for analysis")
    parser.add_argument("--output_dir", type=str, help="Path to save the validation results")
    parser.add_argument("--num_samples", type=int, default=50, help="Number of samples to generate for Red Team simulation")
    parser.add_argument("--poison_ratio", type=float, default=0.2, help="Poison ratio for Red Team simulation")
    args = parser.parse_args()

    print("--- Starting DFIR-Guardrail Pipeline ---")
    model_name = "phi3" 
    blue_team = BlueTeamGuardrail(model_name=model_name)

    # ==========================================
    # --- Operational Mode (KAPE / Production) ---
    # ==========================================
    if args.input_dir and args.output_dir:
        print(f"\n[Operational Mode] Loading real artifacts from: {args.input_dir}")
        dataset = load_real_data(args.input_dir)
        
        if not dataset:
            print("No valid high-risk data found to process. Exiting.")
            return
            
        print(f"-> Loaded {len(dataset)} items containing high-risk fields for analysis.")
        print(f"\n[Blue Team] Scanning artifacts via Ollama (Model: {model_name})...")
        
        start_time = time.time()
        
        # Initialize structured analyst report
        analyst_report = {
            "metadata": {
                "scan_time_seconds": 0,
                "total_artifacts_scanned": len(dataset),
                "threats_detected": 0
            },
            "findings": []
        }

        # Process each artifact sequentially
        for idx, item in enumerate(dataset):
            artifact_for_model = {"Source": item["artifact_source"], "Content": item["content"]}
            predicted_class = blue_team.classify_artifact(artifact_for_model)

            if predicted_class == 1:
                verdict = "Malicious (Prompt Injection Detected)"
            elif predicted_class == -1:
                verdict = "Suspicious (Inference Error / Potential Bypass)"
            else:
                verdict = "Safe (Benign)"

            report_entry = {
                "id": idx + 1,
                "source_file": item["artifact_source"],
                "verdict": verdict
            }
            
            is_threat = (predicted_class == 1 or predicted_class == -1)
            if is_threat:
                analyst_report["metadata"]["threats_detected"] += 1
                report_entry["suspicious_content"] = item["content"]
                if predicted_class == -1:
                    report_entry["error_detail"] = "The guardrail LLM failed to analyze this artifact. Flagged as suspicious under fail-closed security policy."
            
            analyst_report["findings"].append(report_entry)
            
        analyst_report["metadata"]["scan_time_seconds"] = round(time.time() - start_time, 2)
        print(f"-> Processing complete in {analyst_report['metadata']['scan_time_seconds']} seconds.")
        print(f"-> Detected {analyst_report['metadata']['threats_detected']} potential prompt injections.")
        
        os.makedirs(args.output_dir, exist_ok=True)
        output_path = os.path.join(args.output_dir, "guardrail_analysis.json")
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(analyst_report, f, indent=4)
            
        print(f"-> Validation results saved to: {output_path}")

    # ==========================================
    # --- Simulation Mode (Red Team Testing) ---
    # ==========================================
    else:
        print("\n[Simulation Mode] No input/output directories provided. Defaulting to Red Team simulation.")
        red_team = RedTeamPoisoner()
        
        print(f"\n[Red Team] Generating dataset of {args.num_samples} samples with {args.poison_ratio * 100:.0f}% poison ratio...")
        dataset = red_team.generate_dataset(num_samples=args.num_samples, poison_ratio=args.poison_ratio)
        malicious_count = sum(1 for item in dataset if item.get("is_malicious", False))
        print(f"-> Generated {len(dataset)} artifacts ({malicious_count} malicious).")
        
        print(f"\n[Blue Team] Processing sequentially via Ollama (Model: {model_name})...")
        start_time = time.time()
        results = blue_team.process_sequential(dataset)
        elapsed = time.time() - start_time
        print(f"-> Processing complete in {elapsed:.2f} seconds.")
        
        print("\n--- Evaluation Metrics ---")
        metrics = compute_metrics(results)
        for k, v in metrics.items():
            if isinstance(v, float): 
                print(f"{k}: {v:.2%}")
            else: 
                print(f"{k}: {v}")

    print("\n--- DFIR-Guardrail Pipeline Finished ---")

if __name__ == "__main__":
    main()